title: Let's talk about VideoGames
author: Lcv004
email: lcv004@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are going to travel to the fantastic world of imagination, art and technology!

# social links
twitter_username: I dont have # DO NOT include the @ character, or else the build will fail!
github_username:  Lcv004 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
